apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backups
spec:
  capacity:
    storage: 1Mi
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: nfs-provisioner
    name: nfs-backups
  nfs:
    path: /volume1/kubeyournetes
    server: nfs.kubeyournetes.com
