apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backups
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi
  storageClassName: ""
